# =====================================================
# Experiment
# =====================================================
dataset: Shanghai-center-train


work_dir: null
list_dir: null

gpu: "0"
seed: 1234

# =====================================================
# Normalization
# =====================================================
normalization:
  image_means: [101.16, 103.08, 87.93]
  image_stds: [63.32, 56.17, 53.20]

# =====================================================
# Training
# =====================================================
max_epochs: 100
batch_size: 4
base_lr: 0.01

amp: true

# =====================================================
# DataLoader
# =====================================================
dataloader:
  num_workers: 0
  pin_memory: false
  persistent_workers: false
  prefetch_factor: null
  drop_last: true

# =====================================================
# Sampling
# =====================================================
chip_size: 224
num_chips_per_tile: 10
skip_nt: true

# =====================================================
# Label
# =====================================================
label:
  positive_values: [2]
  ignore_value: 255
  ignore_ratio_threshold: 1.0

# =====================================================
# Model
# =====================================================
model:
  width: 64
  image_band: 3
  num_blocks: 5
  need_seg: true

  # MESNet-fast options
  fast_texture: true


# =====================================================
# Pretrained
# =====================================================
last_model: null

# =====================================================
# Optimizer
# =====================================================
optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: false

# =====================================================
# Checkpoint
# =====================================================
checkpoint:
  save_interval: 20
  save_last: true

# =====================================================
# Runtime acceleration
# =====================================================
runtime:
  channels_last: true
  compile: true
  compile_mode: default
  checkpoint: true

# =====================================================
# Loss calculation
# =====================================================
loss:
  weights: [1,1]

